### ISSUE TITLE
Mementos do not currently report information in the Link response header

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#185]
When accessing a memento, a `Link` HTTP response header should be present with information about the memento itself and the archive's other relevant holdings. For example:
```sh
$ ipwb index ipwb/samples/warcs/mementos.warc | ipwb replay
```
from the ipwb root then 
```sh
$ curl -i http://localhost:5000/20140114100000/memento.us/
```
returns
```
HTTP/1.0 200 OK
Content-Type: text/html
Content-Length: 148
X-Archive-Orig-Server: nginx
X-Archive-Orig-Date: Mon, 30 Jan 2017 18:39:49 GMT
X-Archive-Orig-Connection: close
X-Archive-Orig-Vary: Accept-Encoding
Memento-Datetime: Tue, 14 Jan 2014 10:00:00 GMT
Server: InterPlanetary Wayback Replay/0.2017.06.07.1533
Date: Wed, 07 Jun 2017 21:33:10 GMT
```
Compare this to 
```sh
curl -I "http://web.archive.org/web/20170209223454/www.cs.odu.edu/~mkelly/"
```
which returns

```
HTTP/1.1 200 OK
Server: Tengine/2.1.0
Date: Wed, 07 Jun 2017 21:32:35 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 56039
Connection: keep-alive
X-Archive-Orig-content-length: -1
X-Archive-Orig-vary: Accept-Encoding
X-Archive-Orig-server: nginx
X-Archive-Orig-connection: close
X-Archive-Orig-date: Thu, 09 Feb 2017 22:34:54 GMT
X-Archive-Guessed-Charset: UTF-8
Memento-Datetime: Thu, 09 Feb 2017 22:34:54 GMT
Link: <http://www.cs.odu.edu/~mkelly/>; rel="original", <http://web.archive.org/web/timemap/link/http://www.cs.odu.edu/~mkelly/>; rel="timemap"; type="application/link-format", <http://web.archive.org/web/http://www.cs.odu.edu/~mkelly/>; rel="timegate", <http://web.archive.org/web/20130510153903/http://www.cs.odu.edu/~mkelly/>; rel="first memento"; datetime="Fri, 10 May 2013 15:39:03 GMT", <http://web.archive.org/web/20170208170819/http://www.cs.odu.edu/~mkelly/>; rel="prev memento"; datetime="Wed, 08 Feb 2017 17:08:19 GMT", <http://web.archive.org/web/20170209223454/http://www.cs.odu.edu/~mkelly/>; rel="memento"; datetime="Thu, 09 Feb 2017 22:34:54 GMT", <http://web.archive.org/web/20170215231705/http://www.cs.odu.edu/~mkelly/>; rel="next memento"; datetime="Wed, 15 Feb 2017 23:17:05 GMT", <http://web.archive.org/web/20170509152000/http://www.cs.odu.edu/~mkelly/>; rel="last memento"; datetime="Tue, 09 May 2017 15:20:00 GMT"
X-App-Server: wwwb-app19
X-Archive-Playback: 0
X-location: All
X-Page-Cache: MISS
```

**TODO**
- [ ] rel="original" w/ URI-R
- [ ] rel="timemap" w/ metadata specifying CDXJ (as currently implemented) for type, see MemGator
- [ ] first, last, next, prev, and memento (most recent capture) specifications.
