### ISSUE TITLE
Update to test with go-ipfs 0.8.0

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#726]
https://github.com/ipfs/go-ipfs/releases/tag/v0.8.0

Release February 18, 2021.

Related #716 (go-ipfs 0.7.0)

**Comment by machawk1** [comment]
A dependency `ipfshttpclient` is pinned on a max version of 0.7.0 of go-ipfs. I again progressed the fork at https://github.com/machawk1/py-ipfs-http-client to:

1. Remove the max version check.
2. Change the scoping variable/namespace from ipfshttpclient to ipfshttpclient4ipwb so it can be published separately on pypi, as we previously encountered issues of having a Git repo URI in the requirements file.

# TODO
- [ ] Test with main branch at https://github.com/machawk1/py-ipfs-http-client instead of the primary py-ipfs-http-client
- [ ] Release ipfshttpclient4ipwb to Pypi
- [ ] Tweak ipwb to use ipfshttpclient4ipwb instead of ipfshttpclient
- [ ] Release a new version of ipwb to use the new dependency and be compatible with more recent versions of go-ipfs.

**Comment by machawk1** [comment]
https://github.com/ipfs-shipyard/py-ipfs-http-client released version 0.7.0 in March (after the above) and now has a prerelease of 0.8.0a in pypi, so might not need to use fork for tasks.
