### ISSUE TITLE
Release the next version of ipwb (mid-October 2024)

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/ipwb#847]
With the added support for Python 3.12 (#814), among other improvements, a new version of ipwb is warranted, if nothing more than to propagate that support to Pypi and elsewhere.

The target for this is October 17-18, 2024. This ticket shall track the TODOs.

- [x] Wait for the release of kubo 0.31, where the PR (#845) include a new source for ipfs binaries
- [x] Merge in and test with Python 3.13, hopefully without hiccups (see https://github.com/oduwsdl/ipwb/actions/runs/11373922341)
- [x] Update the metadata for Pypi as exhibited in the ipwb source [edce6fe](https://github.com/oduwsdl/ipwb/commit/edce6fe301ff361f5cf4c74b45b977493cdf3423)

...ultimately run `./release.sh`, which will instill the version.

/cc @ibnesayeed

**Comment by machawk1** [comment]
The release GitHub Action is broken:

UNSUPPORTED GITHUB ACTION VERSION \n\n You are using . The branch of this project has been sunset and will not receive any updates, not even security bug fixes. Please, make sure to use a supported version. If you want to pin to v1 major version, use . If you feel adventurous, you may opt to use use instead. A more general recommendation is to pin to exact tags or commit shas. \n\n \n\n ### Oh, and while you are here — #StandWithUkraine \n\n [![SWUbanner]][SWUdocs] \n\n [SWUbanner]: https://raw.githubusercontent.com/vshymanskyy/StandWithUkraine/main/banner-direct-single.svg \n\n [SWUdocs]: https://github.com/vshymanskyy/StandWithUkraine/blob/main/docs/README.md

**Comment by machawk1** [comment]
The dist.yml GitHub Action will need to be resolved to push the latest release on GitHub to Pypi for this GH issue to be closed.

**Comment by machawk1** [comment]
Complete October 24, 2024.
